CREATE TABLE [dbo].[Teamlist]
(
	[Id] INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	POSITION CHAR(25) NOT NULL,
	CONSTRAINT PK_Teamlist PRIMARY KEY(Id)
);
